version: "3.2"

services:

# Sonar  
  sonarr:
    hostname: sonarr
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    network_mode: host
#    ports:
#      - "8989:8989"
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - TZ=${NASFLIX_TZ}
      - UMASK=${NASFLIX_UMASK}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=plex
    volumes:
      - ${NASFLIX_CONFIGS}/sonarr:/config
      - ${NASFLIX_DOWNLOADS}:/nasflix/downloads
      - ${NASFLIX_MEDIA}/tv:/nasflix/media/tv
    restart: unless-stopped     
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

# Radar  
  radarr:
    hostname: radarr
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    network_mode: host
#    ports:
#      - "7878:7878"
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - TZ=${NASFLIX_TZ}
      - UMASK=${NASFLIX_UMASK}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=plex
    volumes:
      - ${NASFLIX_CONFIGS}/radarr:/config
      - ${NASFLIX_DOWNLOADS}:/nasflix/downloads
      - ${NASFLIX_MEDIA}/movies:/nasflix/media/movies
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Lidar
  lidarr:
    hostname: lidarr
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr    
    network_mode: host
#    ports:
#      - 8686:8686
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=plex
    volumes:
      - ${NASFLIX_CONFIGS}/lidarr:/config
      - ${NASFLIX_MEDIA}/music:/nasflix/music #optional
      - ${NASFLIX_DOWNLOADS}:/nasflix/downloads #optional
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

# Jackett 
  jackett:
    hostname: jackett
    container_name: jackett
    image: lscr.io/linuxserver/jackett    
    network_mode: host
#    ports:
#      - 9117:9117
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
    volumes:
      - ${NASFLIX_CONFIGS}/jackett:/config
      - ${NASFLIX_DOWNLOADS}:/downloads
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Organizr
  organizr:
    hostname: organizr
    container_name: organizr
    image: organizr/organizr
    network_mode: bridge    
    ports:
      - 8080:80
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
      - fpm=true
    volumes:
      -  ${NASFLIX_CONFIGS}/organizr:/config
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}


#Resillo Sync 
  sync:
    hostname: sync
    container_name: sync
    image: lscr.io/linuxserver/resilio-sync        
    network_mode: host
    #ports:
    #  - 8888:8888
    #  - 55555:55555
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
    volumes:
      - ${NASFLIX_CONFIGS}/resillo:/config
      - ${NASFLIX_DOWNLOADS}:/downloads
      - ${NASFLIX_DOWNLOADS}:/sync
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}



#volumes:
#  sshvolume:
#    external: true
   

# Medusa 
#  medusa:
#    image: lscr.io/linuxserver/medusa
#    container_name: medusa
#    environment:
#      - PUID=1028
#      - PGID=100
#      - TZ=America/New_York     
#    volumes:
#      - /volume1/nasflix/appdata/medusa:/config
#      - sshvolume:/nasflix/downloads
#      - /volume1/nasflix/media/tv:/nasflix/media/tv
#    ports:
#      - "8081:8081"
#    restart: unless-stopped        

#Resillo Sync
#  sync:
#    user: 1028:100
#    hostname: sync
#    container_name: sync
#    image: resilio/sync      
#    network_mode: host
#    ports:
#        - '8888:8888'
#        - 55555
#    volumes:        
#        - /volume1/nasflix/appdata/resillo:/mnt/sync
#        - /volume1/nasflix/downloads:/mnt/mounted_folders/downloads
#    restart: on-failure
      
# Seedsync
#  seedsync:
#    user: 1028:100      
#    hostname: seedsync
#    container_name: seedsync
#    image: ipsingh06/seedsync
#    ports:
#      - "8800:8800"        
#    volumes:
#      - /volume1/nasflix/downloads:/downloads
#      - /volume1/nasflix/appdata/seedsync:/config
#    restart: unless-stopped