version: "3.2"

networks:
  nasflix:    
    name: nasflix-net
    driver: "bridge"

services:
#
# CORE APPLICATIONS
#

# Nginx
  nginx-proxy:
    hostname: nginx-proxy
    container_name: nginx-proxy
    image: jwilder/nginx-proxy
    networks: 
      - nasflix    
    ports:
      - 80:80
    environment:
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - TZ=${NASFLIX_TZ}
      - UMASK=${NASFLIX_UMASK}
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

# Sonar  
  sonarr:
    hostname: sonarr
    container_name: sonarr
    image: ghcr.io/linuxserver/sonarr
    depends_on:
      - nginx-proxy
    networks: 
      - nasflix    
#    ports:
#      - 8989:8989
    environment:
      - VIRTUAL_HOST=tv.nasflix
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - TZ=${NASFLIX_TZ}
      - UMASK=${NASFLIX_UMASK}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:sonarr
      - TP_THEME=plex
    volumes:
      - ${NASFLIX_CONFIGS}/sonarr:/config
      - ${NASFLIX_DOWNLOADS}:${REMOTE_DOWNLOAD_PATH}
      - ${NASFLIX_MEDIA}/tv:/nasflix/media/tv
    restart: unless-stopped     
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

# Radar  
  radarr:
    hostname: radarr
    container_name: radarr
    image: ghcr.io/linuxserver/radarr
    depends_on:
      - nginx-proxy
    networks: 
      - nasflix   
    #ports:
    #  - 7878:7878
    environment:
      - VIRTUAL_HOST=movies.nasflix
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - TZ=${NASFLIX_TZ}
      - UMASK=${NASFLIX_UMASK}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:radarr
      - TP_THEME=plex
    volumes:
      - ${NASFLIX_CONFIGS}/radarr:/config
      - ${NASFLIX_DOWNLOADS}:${REMOTE_DOWNLOAD_PATH}
      - ${NASFLIX_MEDIA}/movies:/nasflix/media/movies
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Lidar
  lidarr:
    hostname: lidarr
    container_name: lidarr
    image: lscr.io/linuxserver/lidarr
    depends_on:
      - nginx-proxy    
    networks: 
      - nasflix   
    #ports:
    #  - 8686:8686
    environment:
      - VIRTUAL_HOST=music.nasflix
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
      - DOCKER_MODS=ghcr.io/gilbn/theme.park:lidarr
      - TP_THEME=plex
    volumes:
      - ${NASFLIX_CONFIGS}/lidarr:/config
      - ${NASFLIX_MEDIA}/music:/nasflix/music #optional
      - ${NASFLIX_DOWNLOADS}:${REMOTE_DOWNLOAD_PATH}
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

# Jackett 
  jackett:
    hostname: jackett
    container_name: jackett
    image: lscr.io/linuxserver/jackett
    depends_on:
      - nginx-proxy        
    networks: 
      - nasflix   
    #ports:
    #  - 9117:9117
    environment:
      - VIRTUAL_HOST=jackett.nasflix
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
    volumes:
      - ${NASFLIX_CONFIGS}/jackett:/config
    #  - ${NASFLIX_DOWNLOADS}:/downloads
    #  - ${NASFLIX_DOWNLOADS}:${REMOTE_DOWNLOAD_PATH} #blackhole
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Resillo Sync 
  sync:
    hostname: sync
    container_name: sync
    image: lscr.io/linuxserver/resilio-sync
    depends_on:
      - nginx-proxy        
    networks: 
      - nasflix   
    ports:
      - 8888:8888
      - 55555:55555
    environment:
    #  - VIRTUAL_HOST=sync.nasflix
    #  - VIRTUAL_PORT=8888
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
    volumes:
      - ${NASFLIX_CONFIGS}/resillo:/config
      - ${NASFLIX_DOWNLOADS}:/downloads
      - ${NASFLIX_DOWNLOADS}:/sync
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Navidrome music player
  navidrome:
    hostname: navidrome
    container_name: navidrome
    image: deluan/navidrome:latest    
    depends_on:
      - nginx-proxy        
    networks: 
      - nasflix   
    #ports:
    #  - "4533:4533"
    user: ${NASFLIX_PUID}:${NASFLIX_PGID} # should be owner of volumes
    environment:
      - VIRTUAL_HOST=listen.nasflix
    #  - VIRTUAL_PORT=4533
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}      
      # Optional: put your config options customization here. Examples:
      - ND_SCANSCHEDULE=1h
      - ND_LOGLEVEL=info  
      - ND_SESSIONTIMEOUT=24h      
      - ND_SPOTIFY_ID=${NASFLIX_SPOTIFY_ID}
      - ND_SPOTIFY_SECRET=${NASFLIX_SPOTIFY_SECRET}
    volumes:
      - ${NASFLIX_CONFIGS}/navidrome:/data
      - ${NASFLIX_MEDIA}/music:/music:ro      
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}


#Petio
  petio:  
    hostname: petio
    container_name: petio
    image: ghcr.io/petio-team/petio:latest            
    networks:
      - nasflix   
    ports:
      - '7777:7777'
    user: ${NASFLIX_PUID}:${NASFLIX_PGID} # should be owner of volumes
    depends_on:
        - nginx-proxy    
        - mongo
    environment:
      - VIRTUAL_HOST=petio.nasflix
      - VIRTUAL_PORT=7777
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}  
    volumes:
        - ${NASFLIX_CONFIGS}/petio/config:/app/api/config
        # - ./logs:/app/logs
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Mongo - used by Petio
  mongo:
      hostname: mongo
      container_name: mongo
      image: mongo:4.4     
      networks:
        - nasflix   
      user: ${NASFLIX_PUID}:${NASFLIX_PGID} # should be owner of volumes
      depends_on:
        - nginx-proxy          
      environment:
        - PUID=${NASFLIX_PUID}
        - PGID=${NASFLIX_PGID}
        - UMASK=${NASFLIX_UMASK}
        - TZ=${NASFLIX_TZ}      
      volumes:
        - ${NASFLIX_CONFIGS}/petio/db:/data/db
      restart: unless-stopped
      labels:
      - org.hotio.pullio.notify=true
      - org.hotio.pullio.update=true
      - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}




#
# TOOLS AND DASHBOARDS
#

#Bliss Music Tag Management
  bliss:
    hostname: bliss
    container_name: bliss
    image: romancin/bliss
    depends_on:
      - nginx-proxy
    networks:
      - nasflix       
    ports:    
      - 3220:3220
      - 3231:3221
    environment:
      - VIRTUAL_HOST=bliss.nasflix
      - VIRTUAL_PORT=3220
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}      
    volumes:
      - ${NASFLIX_CONFIGS}/bliss:/config
      - ${NASFLIX_MEDIA}/music:/music
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}

#Tautulli
  tautulli:
    hostname: tautulli
    container_name: tautulli
    image: lscr.io/linuxserver/tautulli
    depends_on:
      - nginx-proxy
    networks:
      - nasflix       
    #ports:    
    #  - 8181:8181
    environment:
      - VIRTUAL_HOST=home.nasflix
      - PUID=${NASFLIX_PUID}
      - PGID=${NASFLIX_PGID}
      - UMASK=${NASFLIX_UMASK}
      - TZ=${NASFLIX_TZ}
    volumes:
       -  ${NASFLIX_CONFIGS}/tautulli:/config
    restart: unless-stopped
    labels:
    - org.hotio.pullio.notify=true
    - org.hotio.pullio.update=true
    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}





#Organizr
#  organizr:
#    hostname: organizr
#    container_name: organizr
#    image: organizr/organizr
#    depends_on:
#      - nginx-proxy
#    networks: 
#      - nasflix   
#    # ports:
#    #  - 8080:80    
#    environment:    
#      - DEFAULT_HOST=organizr.nasflix
#      - VIRTUAL_PORT=8080
#      - PUID=${NASFLIX_PUID}
#      - PGID=${NASFLIX_PGID}
#      - UMASK=${NASFLIX_UMASK}
#      - TZ=${NASFLIX_TZ}
#      - fpm=true
#    volumes:
#      -  ${NASFLIX_CONFIGS}/organizr:/config
#    restart: unless-stopped
#    labels:
#    - org.hotio.pullio.notify=true
#    - org.hotio.pullio.update=true
#    - org.hotio.pullio.discord.webhook=${NASFLIX_UPDATE_NOTIFY_WEBHOOK}



